// Literal resource names read from PE tables by category/race (004503f4).
// No executable addresses are retained or called; tests compare the source PE.
#include "game/event_portraits.h"
namespace dl2::data {
std::string_view eliminationPortrait(int observerRace, int defeatedRace) {
    static constexpr std::string_view values[7][7] = {
        {"", "CCELIMD", "CCELIMC", "CCELIMA", "CCELIMF", "CCELIMB", "CCELIME"},
        {"YYELIMF", "", "YYELIMB", "YYELIMA", "YYELIME", "YYELIMC", "YYELIMD"},
        {"HHELIMD", "HHELIMB", "", "HHELIMF", "HHELIMA", "HHELIMC", "HHELIME"},
        {"MMELIMF", "MMELIMB", "MMELIMA", "", "MMELIMC", "MMELIMD", "MMELIME"},
        {"RRELIMD", "RRELIMA", "RRELIME", "RRELIMB", "", "RRELIMF", "RRELIMC"},
        {"TTELIMD", "TTELIME", "TTELIMC", "TTELIMA", "TTELIMB", "", "TTELIMF"},
        {"UUELIMF", "UUELIMC", "UUELIMD", "UUELIME", "UUELIMA", "UUELIMB", ""}
    };
    return observerRace >= 0 && observerRace < 7 && defeatedRace >= 0 && defeatedRace < 7
        ? values[observerRace][defeatedRace] : std::string_view{};
}
namespace {
//004503f4 category15, rows004ca6f8..004ca728.0042d0ac selects a
// successful human pact-offer dialog portrait with one Secondary15 draw.
constexpr std::string_view pactOfferNames[7][15] = {
    {"CCALLYA","CCALLYB","CCALLYC","CCALLYD","CCALLYE","CCALLYF","CCALLYG","CCALLYH","CCALLYI","CCALLYJ","CCALLYK","CCALLYL","CCALLYM","CCALLYN",""},
    {"YYALLYA","YYALLYB","YYALLYC","YYALLYD","YYALLYE","YYALLYF","YYALLYG","YYALLYH","YYALLYI","YYALLYJ","YYALLYK","YYALLYL","YYALLYM","YYALLYN","YYALLYO"},
    {"HHALLYA","HHALLYB","HHALLYC","HHALLYD","HHALLYE","HHALLYF","HHALLYG","HHALLYH","HHALLYI","HHALLYJ","HHALLYK","HHALLYL","HHALLYM","HHALLYN","HHALLYO"},
    {"MMALLYA","MMALLYB","MMALLYC","MMALLYD","MMALLYE","MMALLYF","MMALLYG","MMALLYH","MMALLYI","MMALLYJ","MMALLYK","MMALLYL","MMALLYM","MMALLYN","MMALLYO"},
    {"RRALLYA","RRALLYB","RRALLYC","RRALLYD","RRALLYE","RRALLYF","RRALLYG","RRALLYH","RRALLYI","RRALLYJ","RRALLYK","RRALLYL","RRALLYM","RRALLYN","RRALLYO"},
    {"TTALLYA","TTALLYB","TTALLYC","TTALLYD","TTALLYE","TTALLYF","TTALLYG","TTALLYH","TTALLYI","TTALLYJ","TTALLYK","TTALLYL","TTALLYM","TTALLYN","TTALLYO"},
    {"UUALLYA","UUALLYB","UUALLYC","UUALLYD","UUALLYE","UUALLYF","UUALLYG","UUALLYH","UUALLYI","UUALLYJ","UUALLYK","UUALLYL","UUALLYM","UUALLYN","UUALLYO"}
};
// orig:004503f4 category20, rows004ca810..004ca840. NetBreakPact
// selects one of these five resources using Secondary15%5 for its local
// notification. The special race7/8 tables have no category20 row: their
// computed addresses overlap the unrelated elimination-pointer table.
constexpr std::string_view pactBreakNames[7][5] = {
    {"CCQUITA", "CCQUITB", "CCQUITC", "CCQUITD", "CCQUITE"},
    {"YYQUITA", "YYQUITB", "YYQUITC", "YYQUITD", "YYQUITE"},
    {"HHQUITA", "HHQUITB", "HHQUITC", "HHQUITD", "HHQUITE"},
    {"MMQUITA", "MMQUITB", "MMQUITC", "MMQUITD", "MMQUITE"},
    {"RRQUITA", "RRQUITB", "RRQUITC", "RRQUITD", "RRQUITE"},
    {"TTQUITA", "TTQUITB", "TTQUITC", "TTQUITD", "TTQUITE"},
    {"UUQUITA", "UUQUITB", "UUQUITC", "UUQUITD", "UUQUITE"}
};
constexpr std::string_view names[] = {
    "CCWARNA", "CCWARNB", "CCWARNC", "CCWARND", "CCWARNE", "YYWARNA", "YYWARNB", "YYWARNC",
    "YYWARND", "YYWARNE", "HHWARNA", "HHWARNB", "HHWARNC", "HHWARND", "HHWARNE", "MMWARNA",
    "MMWARNB", "MMWARNC", "MMWARND", "MMWARNE", "RRWARNA", "RRWARNB", "RRWARNC", "RRWARND",
    "RRWARNE", "TTWARNA", "TTWARNB", "TTWARNC", "TTWARND", "TTWARNE", "UUWARNA", "UUWARNB",
    "UUWARNC", "UUWARND", "UUWARNE", "CCGRANA", "CCGRANB", "CCGRANC", "CCGRAND", "CCGRANE",
    "YYGRANA", "YYGRANB", "YYGRANC", "YYGRAND", "YYGRANE", "HHGRANA", "HHGRANB", "HHGRANC",
    "HHGRAND", "HHGRANE", "MMGRANA", "MMGRANB", "MMGRANC", "MMGRAND", "MMGRANE", "RRGRANA",
    "RRGRANB", "RRGRANC", "RRGRAND", "RRGRANE", "TTGRANA", "TTGRANB", "TTGRANC", "TTGRAND",
    "TTGRANE", "UUGRANA", "UUGRANB", "UUGRANC", "UUGRAND", "UUGRANE", "CCBRANA", "CCBRANB",
    "CCBRANC", "CCBRAND", "CCBRANE", "YYBRANA", "YYBRANB", "YYBRANC", "YYBRAND", "YYBRANE",
    "HHBRANA", "HHBRANB", "HHBRANC", "HHBRAND", "HHBRANE", "MMBRANA", "MMBRANB", "MMBRANC",
    "MMBRAND", "MMBRANE", "RRBRANA", "RRBRANB", "RRBRANC", "RRBRAND", "RRBRANE", "TTBRANA",
    "TTBRANB", "TTBRANC", "TTBRAND", "TTBRANE", "UUBRANA", "UUBRANB", "UUBRANC", "UUBRAND",
    "UUBRANE", "CCGCONA", "CCGCONB", "CCGCONC", "CCGCOND", "CCGCONE", "YYGCONA", "YYGCONB",
    "YYGCONC", "YYGCOND", "YYGCONE", "HHGCONA", "HHGCONB", "HHGCONC", "HHGCOND", "HHGCONE",
    "MMGCONA", "MMGCONB", "MMGCONC", "MMGCOND", "MMGCONE", "RRGCONA", "RRGCONB", "RRGCONC",
    "RRGCOND", "RRGCONE", "TTGCONA", "TTGCONB", "TTGCONC", "TTGCOND", "TTGCONE", "UUGCONA",
    "UUGCONB", "UUGCONC", "UUGCOND", "UUGCONE", "CCBCONA", "CCBCONB", "CCBCONC", "CCBCOND",
    "CCBCONE", "YYBCONA", "YYBCONB", "YYBCONC", "YYBCOND", "YYBCONE", "HHBCONA", "HHBCONB",
    "HHBCONC", "HHBCOND", "HHBCONE", "MMBCONA", "MMBCONB", "MMBCONC", "MMBCOND", "MMBCONE",
    "RRBCONA", "RRBCONB", "RRBCONC", "RRBCOND", "RRBCONE", "TTBCONA", "TTBCONB", "TTBCONC",
    "TTBCOND", "TTBCONE", "UUBCONA", "UUBCONB", "UUBCONC", "UUBCOND", "UUBCONE", "CCEVNTA",
    "CCEVNTB", "CCEVNTC", "CCEVNTD", "CCEVNTE", "YYEVNTA", "YYEVNTB", "YYEVNTC", "YYEVNTD",
    "YYEVNTE", "HHEVENTA", "HHEVENTB", "HHEVENTC", "HHEVENTD", "HHEVENTE", "MMEVNTA", "MMEVNTB",
    "MMEVNTC", "MMEVNTD", "MMEVNTE", "RREVNTA", "RREVNTB", "RREVNTC", "RREVNTD", "RREVNTE",
    "TTEVNTA", "TTEVNTB", "TTEVNTC", "TTEVNTD", "TTEVNTE", "UUEVNTA", "UUEVNTB", "UUEVNTC",
    "UUEVNTD", "UUEVNTE", "CCXENOA", "CCXENOB", "CCXENOC", "CCXENOD", "YYXENOA", "YYXENOB",
    "YYXENOC", "YYXENOD", "HHXENOA", "HHXENOB", "HHXENOC", "HHXENOD", "MMXENOA", "MMXENOB",
    "MMXENOC", "MMXENOD", "RRXENOA", "RRXENOB", "RRXENOC", "RRXENOD", "TTXENOA", "TTXENOB",
    "TTXENOC", "TTXENOD", "UUXENOA", "UUXENOB", "UUXENOC", "UUXENOD", "CCEXITA", "CCEXITB",
    "CCEXITC", "CCEXITD", "CCEXITE", "CCEXITF", "CCEXITG", "CCEXITH", "CCEXITI", "CCEXITJ",
    "CCEXITK", "CCEXITL", "YYEXITA", "YYEXITB", "YYEXITC", "YYEXITD", "YYEXITE", "YYEXITF",
    "YYEXITG", "YYEXITH", "YYEXITI", "YYEXITJ", "YYEXITK", "YYEXITL", "HHEXITA", "HHEXITB",
    "HHEXITC", "HHEXITD", "HHEXITE", "HHEXITF", "HHEXITG", "HHEXITH", "HHEXITI", "HHEXITJ",
    "HHEXITK", "HHEXITL", "MMEXITA", "MMEXITB", "MMEXITC", "MMEXITD", "MMEXITE", "MMEXITF",
    "MMEXITG", "MMEXITH", "MMEXITI", "MMEXITJ", "MMEXITK", "MMEXITL", "RREXITA", "RREXITB",
    "RREXITC", "RREXITD", "RREXITE", "RREXITF", "RREXITG", "RREXITH", "RREXITI", "RREXITJ",
    "RREXITK", "RREXITL", "TTEXITA", "TTEXITB", "TTEXITC", "TTEXITD", "TTEXITE", "TTEXITF",
    "TTEXITG", "TTEXITH", "TTEXITI", "TTEXITJ", "TTEXITK", "TTEXITL", "UUEXITA", "UUEXITB",
    "UUEXITC", "UUEXITD", "UUEXITE", "UUEXITF", "UUEXITG", "UUEXITH", "UUEXITI", "UUEXITJ",
    "UUEXITK", "UUEXITL", "CCTECHA", "CCTECHB", "CCTECHC", "YYTECHA", "YYTECHB", "YYTECHC",
    "HHTECHA", "HHTECHB", "HHTECHC", "MMTECHA", "MMTECHB", "MMTECHC", "RRTECHA", "RRTECHB",
    "RRTECHC", "TTTECHA", "TTTECHB", "TTTECHC", "UUTECHA", "UUTECHB", "UUTECHC", "CCTECHD",
    "CCTECHE", "CCTECHF", "YYTECHD", "YYTECHE", "YYTECHF", "HHTECHD", "HHTECHE", "HHTECHF",
    "MMTECHD", "MMTECHE", "MMTECHF", "RRTECHD", "RRTECHE", "RRTECHF", "TTTECHD", "TTTECHE",
    "TTTECHF", "UUTECHD", "UUTECHE", "UUTECHF", "CCDAMAA", "CCDAMAB", "CCDAMAC", "YYDAMAA",
    "YYDAMAB", "YYDAMAC", "HHDAMAA", "HHDAMAB", "HHDAMAC", "MMDAMAA", "MMDAMAB", "MMDAMAC",
    "RRDAMAA", "RRDAMAB", "RRDAMAC", "TTDAMAA", "TTDAMAB", "TTDAMAC", "UUDAMAA", "UUDAMAB",
    "UUDAMAC", "CCRSLTA", "CCRSLTB", "YYRSLTA", "YYRSLTB", "HHRSLTA", "HHRSLTB", "MMRSLTA",
    "MMRSLTB", "RRRSLTA", "RRRSLTB", "TTRSLTA", "TTRSLTB", "UURSLTA", "UURSLTB", "CCELIMD",
    "CCELIMC", "CCELIMA", "CCELIMB", "CCELIMF", "CCELIME", "YYELIMD", "YYELIMC", "YYELIMA",
    "YYELIMB", "YYELIMF", "YYELIME", "HHELIMD", "HHELIMC", "HHELIMA", "HHELIMB", "HHELIMF",
    "HHELIME", "MMELIMD", "MMELIMC", "MMELIMA", "MMELIMB", "MMELIMF", "MMELIME", "RRELIMD",
    "RRELIMC", "RRELIMA", "RRELIMB", "RRELIMF", "RRELIME", "TTELIMD", "TTELIMC", "TTELIMA",
    "TTELIMB", "TTELIMF", "TTELIME", "UUELIMD", "UUELIMC", "UUELIMA", "UUELIMB", "UUELIMF",
    "UUELIME", "CCDFTWA", "YYDFTWA", "HHDFTWA", "MMDFTWA", "RRDFTWA", "TTDFTWA", "UUDFTWA",
    "CCDFTCA", "YYDFTCA", "HHDFTCA", "MMDFTCA", "RRDFTCA", "TTDFTCA", "UUDFTCA",
};
struct Row { int category, race; uint32_t first, count; };
constexpr Row rows[] = {
    {1, 0, 0, 5},
    {1, 1, 5, 5},
    {1, 2, 10, 5},
    {1, 3, 15, 5},
    {1, 4, 20, 5},
    {1, 5, 25, 5},
    {1, 6, 30, 5},
    {2, 0, 35, 5},
    {2, 1, 40, 5},
    {2, 2, 45, 5},
    {2, 3, 50, 5},
    {2, 4, 55, 5},
    {2, 5, 60, 5},
    {2, 6, 65, 5},
    {3, 0, 70, 5},
    {3, 1, 75, 5},
    {3, 2, 80, 5},
    {3, 3, 85, 5},
    {3, 4, 90, 5},
    {3, 5, 95, 5},
    {3, 6, 100, 5},
    {4, 0, 105, 5},
    {4, 1, 110, 5},
    {4, 2, 115, 5},
    {4, 3, 120, 5},
    {4, 4, 125, 5},
    {4, 5, 130, 5},
    {4, 6, 135, 5},
    {5, 0, 140, 5},
    {5, 1, 145, 5},
    {5, 2, 150, 5},
    {5, 3, 155, 5},
    {5, 4, 160, 5},
    {5, 5, 165, 5},
    {5, 6, 170, 5},
    {6, 0, 175, 5},
    {6, 1, 180, 5},
    {6, 2, 185, 5},
    {6, 3, 190, 5},
    {6, 4, 195, 5},
    {6, 5, 200, 5},
    {6, 6, 205, 5},
    {7, 0, 210, 4},
    {7, 1, 214, 4},
    {7, 2, 218, 4},
    {7, 3, 222, 4},
    {7, 4, 226, 4},
    {7, 5, 230, 4},
    {7, 6, 234, 4},
    {8, 0, 238, 12},
    {8, 1, 250, 12},
    {8, 2, 262, 12},
    {8, 3, 274, 12},
    {8, 4, 286, 12},
    {8, 5, 298, 12},
    {8, 6, 310, 12},
    {12, 0, 322, 3},
    {12, 1, 325, 3},
    {12, 2, 328, 3},
    {12, 3, 331, 3},
    {12, 4, 334, 3},
    {12, 5, 337, 3},
    {12, 6, 340, 3},
    {13, 0, 343, 3},
    {13, 1, 346, 3},
    {13, 2, 349, 3},
    {13, 3, 352, 3},
    {13, 4, 355, 3},
    {13, 5, 358, 3},
    {13, 6, 361, 3},
    {21, 0, 364, 3},
    {21, 1, 367, 3},
    {21, 2, 370, 3},
    {21, 3, 373, 3},
    {21, 4, 376, 3},
    {21, 5, 379, 3},
    {21, 6, 382, 3},
    {24, 0, 385, 2},
    {24, 1, 387, 2},
    {24, 2, 389, 2},
    {24, 3, 391, 2},
    {24, 4, 393, 2},
    {24, 5, 395, 2},
    {24, 6, 397, 2},
    {25, 0, 399, 6},
    {25, 1, 405, 6},
    {25, 2, 411, 6},
    {25, 3, 417, 6},
    {25, 4, 423, 6},
    {25, 5, 429, 6},
    {25, 6, 435, 6},
    {26, 0, 441, 1},
    {26, 1, 442, 1},
    {26, 2, 443, 1},
    {26, 3, 444, 1},
    {26, 4, 445, 1},
    {26, 5, 446, 1},
    {26, 6, 447, 1},
    {27, 0, 448, 1},
    {27, 1, 449, 1},
    {27, 2, 450, 1},
    {27, 3, 451, 1},
    {27, 4, 452, 1},
    {27, 5, 453, 1},
    {27, 6, 454, 1},
};
}
std::span<const std::string_view> eventPortraitNames(int race, int category) {
    if (category == 15 && race >= 0 && race < 7) return {pactOfferNames[race],race==0?size_t(14):size_t(15)};
    if (category == 20 && race >= 0 && race < 7) return pactBreakNames[race];
    for (const auto& row : rows) if (row.race == race && row.category == category)
        return {names + row.first, row.count};
    return {};
}
}
