// sprite_tables.h - sprite definition tables of DEADLOCK.EXE (generated by tools/extract_sprites.py; do not edit).
// See docs/SPRITES.md for the layout and the addresses in the original executable.
#pragma once
#include <cstddef>
#include <cstdint>

namespace dl2::sprites {

// One frame: w*h 8 bpp pixels at fileOffset in SPRITENW.DAT. hotX/hotY are added to the object position
// when drawing (DrawSprite FUN_00444cf4: screenX = (x >> 8) + hotX).
struct SpriteDef {
    int16_t hotX, hotY;
    int16_t w, h;
    uint32_t fileOffset;
};

// One record of the sprite type table (0x004D02F4, 12 bytes in the EXE).
struct SpriteTypeDef {
    uint16_t firstFrame;   // index into kFrames
    uint16_t frameCount;
    uint16_t script;       // word offset into kAnimScript, kNoScript if none
    uint16_t rate;         // ANIM timer reload (frames between script steps)
    uint16_t flags;        // ANIM flags OR-ed into the object on creation
    const char* name;      // reconstructed name (not in the EXE)
};

// Tables that are not reachable through the type table (dialog pictures, race emblems ...).
struct ExtraTableDef {
    uint32_t address;      // address of the table in the EXE
    const char* name;
    uint16_t firstFrame;
    uint16_t frameCount;
};

struct Rgb8 { uint8_t r, g, b; };

constexpr uint16_t kNoScript = 0xFFFF;
constexpr int kTypeCount = 427;
constexpr int kFrameCount = 6917;
constexpr int kExtraTableCount = 16;
constexpr int kAnimScriptWords = 2261;
constexpr int kWorldCount = 7;

extern const SpriteDef kFrames[kFrameCount];
extern const SpriteTypeDef kSpriteTypes[kTypeCount];
extern const ExtraTableDef kExtraTables[kExtraTableCount];

// Anim script stream (FUN_00445270 interpreter). Pointer operands were relocated to word offsets:
// a u32 pointer in the EXE is stored as {offset, 0xFFFF}.
extern const uint16_t kAnimScript[kAnimScriptWords];
constexpr uint16_t kMissileScript = 2006;    // script forced for missiles (DAT_00519cce)

// Palettes (RGB, converted from the RGBQUAD tables of the EXE).
extern const Rgb8 kPaletteMaster[256];            // 0x0051ACA4
extern const Rgb8 kPaletteWorld[kWorldCount][64];  // 0x00519ECC, entries 16..79 per planet type
extern const Rgb8 kPaletteFixed6[6];              // 0x0051A5CC, entries 10..15
extern const Rgb8 kPaletteFixed112[112];          // 0x0051A5E4, entries 144..255
extern const Rgb8 kPaletteDialog64[64];           // 0x0051A7A4, entries 80..143 for XenoWinG pictures
extern const Rgb8 kWindowsStaticColours[20];      // entries 0..9 and 246..255 on an 8 bpp display

// Sprite type lists used by the loaders.
extern const uint16_t kGlobalSpriteTypes[17];     // 0x004D4DD0 (PreloadSprite2)
extern const uint16_t kCombatSpriteTypesA[14];    // 0x004D4E14 (LoadCombatSprites, settlement)
extern const uint16_t kCombatSpriteTypesB[6];    // 0x004D4E4C (LoadCombatSprites)

// Building / unit tables (sprite type columns only).
struct BuildingSprite { const char* name; int16_t spriteType; uint8_t sizeClass; uint8_t footprint; };
struct UnitSprite { const char* name; int16_t spriteType; int16_t spriteType2; uint8_t unitClass; };
extern const BuildingSprite kBuildings[49];
extern const UnitSprite kUnits[38];

}  // namespace dl2::sprites
